* NumPy is a Python library used for working with arrays.
* NumPy stands for Numerical Python.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists


In [97]:
import numpy as np

In [98]:
a=np.array([])
b=np.array([1,2,3,4])
c=np.array([[1,2,],[5,6]])
d=np.array([[1,2,4],[5,6,8],
            [9,11,12]])
e=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [99]:
a 

array([], dtype=float64)

In [100]:
type(a)
#The N-dimensional array (ndarray)


numpy.ndarray

In [101]:
print(a)

[]


In [102]:
c.ndim
#ndim is used to know the number of dimensions in the array(as in this case it is 2 dimensions/we can also know the dimensions by counting the number of brackets at the starting of the array)

2

In [103]:
d.ndim

2

In [104]:
b

array([1, 2, 3, 4])

In [105]:
type(b)


numpy.ndarray

In [106]:
b.size
#This will give you Number of elements in the array

4

In [107]:
a.size

0

In [108]:
c.size

4

In [109]:
d.size

9

In [110]:
#Shape gives you the (number of rows,number of columns) in the array
c.shape

(2, 2)

In [111]:
d.shape

(3, 3)

In [112]:
b.shape

(4,)

In [113]:
a.shape

(0,)

In [114]:
print(d)

[[ 1  2  4]
 [ 5  6  8]
 [ 9 11 12]]


In [115]:
d
#Here in the output small difference (which is showing array)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 11, 12]])

In [116]:
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [117]:
e.ndim

3

In [118]:
e.shape

(1, 3, 3)

In [119]:
print(d[[0],[0]])
print(d[[1],[0]])
#for printing a specific element in the array
#d(p[[Row],[Collumn]])

[1]
[5]


In [120]:
#In order to print a Row and using of slicing
print(d[0][0:3:1])
print(d[1][0:3:1])
print(d[2][0:2:1])
print(d[0,0:4:1])#Another method(going inside first row then iterating collumns)

[1 2 4]
[5 6 8]
[ 9 11]
[1 2 4]


In [121]:
d[0:3:1]#whole list is printing which is an array first row then second row and then third
#This is printing the whole array as we are not slicing in the particular row


array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 11, 12]])

In [122]:
print(d[0:4,1:])
#This is first go inside row then iterate the collumns( in this case from 2nd collumn)

print(d[0:2,0:2])#printing two rows and two collumns
print(d[:2,0:3])#printing two rows and three collumns



[[ 2  4]
 [ 6  8]
 [11 12]]
[[1 2]
 [5 6]]
[[1 2 4]
 [5 6 8]]


In [123]:

#Creating and list of number from 1-9(range=0-10)
print(np.arange(0,10))


[0 1 2 3 4 5 6 7 8 9]


* Reshaping Of Arrays

In [124]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
np.arange(0,12).reshape(2,6)
#Reshaping the array again in 2 rows and 6 collumns


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

* Some Other Features of Numpy

In [126]:
#Finding square roots of a number
np.sqrt(64)

8.0

In [127]:
#To find maximum present element in the array
d.max()
#To find minimum present element in the array
# d.min()

12

In [128]:
#Returns the average of the array elements
d.mean()

6.444444444444445

In [129]:
#It is used to find the index of the maximum element present in the array
d.argmax()

8

In [130]:
#It is used to find the index of the minimum element present in the array
d.argmin()

0

In [131]:
#Applying Arithmetic operators as a whole in array
d+2#Showing every element of the array with +2
#similarly we can also use d*,d/,d-


array([[ 3,  4,  6],
       [ 7,  8, 10],
       [11, 13, 14]])

# Random
* The random module is part of the NumPy library

In [132]:
#It Create an array of the given shape and populate it with random samples,with range (0,1)
import random
a=np.random.rand(2,2)
a


array([[0.56336457, 0.10073793],
       [0.41174808, 0.02760626]])

In [133]:
print(type(a))

<class 'numpy.ndarray'>


In [134]:
#randn(): creates random number on the normal distribution ("with replacement") with mean 0 and standard deviation 1.
b=np.random.randn(2,2)
b

array([[-0.65008763, -0.55460887],
       [ 1.51347602, -0.03225997]])

In [135]:
c=np.random.randint(1,10,12).reshape(3,4)
#randint(Low,High,sizeof(array)).reshape("according to its size")
c

array([[4, 6, 7, 4],
       [8, 3, 4, 5],
       [7, 6, 1, 8]])

In [136]:
d=np.random.randint(90,100,12).reshape(6,2)
d

array([[97, 92],
       [99, 91],
       [92, 96],
       [91, 97],
       [96, 93],
       [92, 92]])

In [137]:
c.sum()
#This will give you the sum of all the element in the array


63

In [138]:
#In order to find sum of Row wise
c.sum(axis=1)

array([21, 20, 22])

In [139]:
#In order to find sum of collumn wise
c.sum(axis=0)

array([19, 15, 12, 17])

In [140]:
#In order to Choose random item from the list
list=['Hello','bye',1,3,4,'world']
val=random.choice(list)
val2=random.choices(list,k=2)#This will print Two random choices from the list
print(val,'\n',val2)


Hello 
 ['world', 'bye']


In [141]:
#In order to shuffle the list
z=random.shuffle(list)
print(list)

[4, 1, 'Hello', 'bye', 3, 'world']


# OS
* The OS module in Python provides functions for interacting with the operating system
* The OS comes under Python's standard utility modules.

In [142]:
import os

In [143]:
#In order to Make Folder using Module os
os.mkdir("Folder_through_OS")
#It will thorw error if you run it again as file already exist with that name

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'Folder_through_OS'

In [144]:
#This is get you the Location of the current Working Directory
os.getcwd()

'c:\\ML Training\\Numpy'

In [145]:
#In oder to know What lies inside any folder 
os.listdir('c:\\ML Training')

['.git', 'Assignment', 'Notes', 'Numpy', 'readme.md']

In [146]:
#It is used to change Directory
os.chdir('C:\ML Training')

# Calender And Datetime

In [147]:
import datetime as dt
import calendar

In [148]:
#This will give You the current time
#datetime and date are classes in datetime 
a=dt.datetime.now()#now() for tme
print(a)

2022-10-13 23:29:45.444340


In [149]:
#This will give you current date
b=dt.date.today()#today for date
print(b)

2022-10-13


In [ ]:
m=calendar.calendar(2022)
print(m)

                                  2022

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 

In [ ]:
#In order to print a month of a year
print(calendar.month(2002,11))

   November 2002
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [152]:
print(calendar.month(2002,12))

   December 2002
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



In [ ]:
#Fibonacci Series Code
def fib(n):
     a, b = 0, 1
     while a < n:
        print(a, end=' ')
        a, b = b, a+b
     print()
fib(1000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 
