* NumPy is a Python library used for working with arrays.
* NumPy stands for Numerical Python.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists

In [2]:
import numpy as np

In [68]:
a=np.array([])
b=np.array([1,2,3,4])
c=np.array([[1,2,],[5,6]])
d=np.array([[1,2,4],[5,6,8],
            [9,11,12]])
e=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [4]:
a 

array([], dtype=float64)

In [5]:
type(a)
#The N-dimensional array (ndarray)


numpy.ndarray

In [6]:
print(a)

[]


In [7]:
c.ndim
#ndim is used to know the number of dimensions in the array(as in this case it is 2 dimensions/we can also know the dimensions by counting the number of brackets at the starting of the array)

2

In [8]:
d.ndim

2

In [9]:
b

array([1, 2, 3, 4])

In [10]:
type(b)


numpy.ndarray

In [11]:
b.size
#This will give you Number of elements in the array

4

In [12]:
a.size

0

In [13]:
c.size

4

In [14]:
d.size

9

In [15]:
#Shape gives you the (number of rows,number of columns) in the array
c.shape

(2, 2)

In [16]:
d.shape

(3, 3)

In [17]:
b.shape

(4,)

In [18]:
a.shape

(0,)

In [19]:
print(d)

[[ 1  2  4]
 [ 5  6  8]
 [ 9 11 12]]


In [20]:
d
#Here in the output small difference (which is showing array)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 11, 12]])

In [69]:
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [70]:
e.ndim

3

In [71]:
e.shape

(1, 3, 3)

In [21]:
print(d[[0],[0]])
print(d[[1],[0]])
#for printing a specific element in the array
#d(p[[Row],[Collumn]])

[1]
[5]


In [22]:
#In order to print a Row and using of slicing
print(d[0][0:3:1])
print(d[1][0:3:1])
print(d[2][0:2:1])
print(d[0,0:4:1])#Another method(going inside first row then iterating collumns)

[1 2 4]
[5 6 8]
[ 9 11]
[1 2 4]


In [23]:
d[0:3:1]#whole list is printing which is an array first row then second row and then third
#This is printing the whole array as we are not slicing in the particular row


array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 11, 12]])

In [24]:
print(d[0:4,1:])
#This is first go inside row then iterate the collumns( in this case from 2nd collumn)

print(d[0:2,0:2])#printing two rows and two collumns
print(d[:2,0:3])#printing two rows and three collumns



[[ 2  4]
 [ 6  8]
 [11 12]]
[[1 2]
 [5 6]]
[[1 2 4]
 [5 6 8]]


In [25]:
list (range(0,10))
#Creating and list of number from 1-9(range=0-10)

# print(np.arange(0,10)) Another way of using arrange as a function (output is same)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

* Reshaping Of Arrays

In [26]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
np.arange(0,12).reshape(2,6)
#Reshaping the array again in 2 rows and 6 collumns


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

* Some Other Features of Numpy

In [28]:
#Finding square roots of a number
np.sqrt(64)

8.0

In [29]:
#To find maximum present element in the array
d.max()
#To find minimum present element in the array
# d.min()

12

In [30]:
#Returns the average of the array elements
d.mean()

6.444444444444445

In [31]:
#It is used to find the index of the maximum element present in the array
d.argmax()

8

In [32]:
#It is used to find the index of the minimum element present in the array
d.argmin()

0

In [33]:
#Applying Arithmetic operators as a whole in array
d+2#Showing every element of the array with +2
#similarly we can also use d*,d/,d-


array([[ 3,  4,  6],
       [ 7,  8, 10],
       [11, 13, 14]])

# Random

In [51]:
#It Create an array of the given shape and populate it with random samples,with range (0,1)

a=np.random.rand(2,2)
a


array([[0.28072435, 0.94288775],
       [0.39941822, 0.41215939]])

In [42]:
print(type(a))

<class 'numpy.ndarray'>


In [53]:
#randn(): creates random number on the normal distribution ("with replacement") with mean 0 and standard deviation 1.
b=np.random.randn(2,2)
b

array([[-0.60431005, -0.93144512],
       [-0.15889813,  1.51200369]])

In [60]:
c=np.random.randint(1,10,12).reshape(3,4)
#randint(Low,High,sizeof(array)).reshape("according to its size")
c

array([[9, 9, 1, 2],
       [4, 2, 5, 9],
       [6, 1, 4, 5]])

In [62]:
d=np.random.randint(90,100,12).reshape(6,2)
d

array([[92, 98],
       [94, 97],
       [96, 94],
       [94, 92],
       [90, 92],
       [98, 97]])

In [63]:
c.sum()
#This will give you the sum of all the element in the array


57

In [65]:
#In order to find sum of Row wise
c.sum(axis=1)

array([21, 20, 16])

In [67]:
#In order to find sum of collumn wise
c.sum(axis=0)

array([19, 12, 10, 16])